version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: readerai_backend
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: readerai_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
# Note: Before running `docker-compose up`, you need to build the frontend:
# cd frontend
# npm install
# npm run build
# cd ..
