[project]
name = "readerai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dspy>=2.6.3",
    "ipython>=8.32.0",
    "python-dotenv>=1.0.1",
]

[tool.setuptools.package-dir]
"" = "src"