# Consolidated outputs for easy reference

output "infrastructure_summary" {
  value = {
    audio_cache_bucket = aws_s3_bucket.audio_cache.id
    audio_base_url     = "https://${aws_s3_bucket.audio_cache.id}.s3.${var.aws_region}.amazonaws.com"
    backend_role_arn   = aws_iam_role.backend_role.arn
    region            = var.aws_region
    environment       = var.environment
  }
  description = "Summary of all infrastructure endpoints and identifiers"
}

# Example .env file content
output "env_file_content" {
  value = <<-EOT
# Generated by Terraform - ${timestamp()}
AWS_REGION=${var.aws_region}
AUDIO_CACHE_BUCKET=${aws_s3_bucket.audio_cache.id}
AUDIO_BASE_URL=https://${aws_s3_bucket.audio_cache.id}.s3.${var.aws_region}.amazonaws.com
BACKEND_ROLE_ARN=${aws_iam_role.backend_role.arn}
ENVIRONMENT=${var.environment}
EOT
  description = "Environment variables for backend configuration"
  sensitive   = false
}
